### ISSUE TITLE
[1.12.x] Crash when rendering subtitles

### ISSUE THREAD

**Issue by Gentle888** [crazysnailboy/AdvancedHUD#2]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.108.jar)
  BetterFontsCore (TTFR-1.12.1-1.9.1.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 9/20/17 3:14 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.gui.GuiSubtitleOverlay.func_184068_a(SourceFile:81)
	at net.minecraftforge.client.GuiIngameForge.renderSubtitles(GuiIngameForge.java:233)
	at advancedhud.client.GuiAdvancedHUD.renderSubtitles(GuiAdvancedHUD.java:317)
	at advancedhud.client.GuiAdvancedHUD.func_175180_a(GuiAdvancedHUD.java:102)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1397)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Thread.getStackTrace(Unknown Source)

-- World Downloader Mod - Core --
Details:
	WDL version: 4.0.1.0
	Minecraft version: Minecraft 1.12.1 (1.12.1/fml,forge/Forge)
	Expected version: 1.12.1
	Protocol version: 338
	Data version: 1241
	File location: ~~ERROR~~ IllegalArgumentException: URI is not hierarchical
Stacktrace:
	at java.lang.Thread.getStackTrace(Unknown Source)
	at net.minecraft.crash.CrashReportCategory.func_85073_a(CrashReportCategory.java:116)
	at net.minecraft.crash.CrashReport.func_85057_a(CrashReport.java:352)
	at wdl.WDL.addInfoToCrash(WDL.java:1469)
	at wdl.WDLHooks.onCrashReportPopulateEnvironment(WDLHooks.java:371)
	at net.minecraft.crash.CrashReport.handler$onCrashReportPopulateEnvironment$zze000(CrashReport.java:514)
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:144)
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- World Downloader Mod - Extensions --
Details:
	Number loaded: : 2
	Hologram: Id: Hologram
Version: 2.0
Display name: Hologram support
Main author: Pokechu22
Description: 
Provides basic support for disabling holograms.
Main class: wdl.HologramHandler
Containing file: Unknown (java.lang.IllegalArgumentException: URI is not hierarchical)
Implemented interfaces (2)
0: wdl.api.IEntityManager
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: net.minecraft.launchwrapper.LaunchClassLoader@ba8a1dc (net.minecraft.launchwrapper.LaunchClassLoader)
Annotations (0)

	EntityRealigner: Id: EntityRealigner
Version: 1.0
Display name: Entity realigner
Main author: Pokechu22
Description: 
Realigns entities to their serverside position to deal with entities that drift clientside (for example, boats).
Main class: wdl.EntityRealigner
Containing file: Unknown (java.lang.IllegalArgumentException: URI is not hierarchical)
Implemented interfaces (2)
0: wdl.api.IEntityEditor
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: net.minecraft.launchwrapper.LaunchClassLoader@ba8a1dc (net.minecraft.launchwrapper.LaunchClassLoader)
Annotations (0)


-- World Downloader Mod - State --
Details:
	minecraft: net.minecraft.client.Minecraft@23657729
	worldClient: ~~NULL~~
	networkManager: ~~NULL~~
	thePlayer: ~~NULL~~
	windowContainer: ~~NULL~~
	lastClickedBlock: ~~NULL~~
	lastEntity: ~~NULL~~
	saveHandler: ~~NULL~~
	chunkLoader: ~~NULL~~
	newTileEntities: {}
	newEntities: {}
	newMapDatas: {}
	downloading: false
	isMultiworld: false
	propsFound: false
	startOnChange: false
	overrideLastModifiedCheck: false
	saving: false
	worldLoadingDeferred: false
	worldName: WorldDownloaderERROR
	baseFolderName: WorldDownloaderERROR

-- World Downloader Mod - Base properties --
Details:
	-: empty

-- World Downloader Mod - World properties --
Details:
	-: empty

-- World Downloader Mod - Global properties --
Details:
	TutorialShown: true
	UpdateETag: "e7b28994759824b36bd308117b46b122"

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Gentle'/236, l='MpServer', x=-168.23, y=91.00, z=393.62]]
	Chunk stats: MultiplayerChunkCache: 270, 270
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-248,64,236), Chunk: (at 8,4,12 in -16,14; contains blocks -256,0,224 to -241,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 11732 game time, 3577 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 102 total; [EntityCreeper['Creeper'/260, l='MpServer', x=-120.50, y=28.00, z=453.50], EntityZombie['Zombie'/264, l='MpServer', x=-135.50, y=18.00, z=461.50], EntityCreeper['Creeper'/265, l='MpServer', x=-136.49, y=33.00, z=455.18], EntityItem['item.item.rottenFlesh'/271, l='MpServer', x=-217.88, y=73.00, z=438.70], EntitySheep['Sheep'/272, l='MpServer', x=-113.50, y=71.00, z=471.50], EntitySheep['Sheep'/273, l='MpServer', x=-115.10, y=70.00, z=469.50], EntityZombie['Zombie'/274, l='MpServer', x=-102.50, y=26.00, z=452.50], EntitySkeleton['Skeleton'/275, l='MpServer', x=-165.45, y=42.00, z=440.72], EntityZombie['Zombie'/284, l='MpServer', x=-142.50, y=26.00, z=443.50], EntityZombie['Zombie'/285, l='MpServer', x=-141.50, y=36.00, z=442.50], EntityCreeper['Creeper'/286, l='MpServer', x=-128.78, y=33.00, z=448.59], EntitySkeleton['Skeleton'/290, l='MpServer', x=-146.21, y=26.00, z=445.50], EntityZombie['Zombie'/291, l='MpServer', x=-145.50, y=26.00, z=441.50], EntityZombie['Zombie'/292, l='MpServer', x=-148.50, y=26.00, z=437.50], EntitySkeleton['Skeleton'/293, l='MpServer', x=-166.50, y=39.00, z=452.50], EntityBat['Bat'/303, l='MpServer', x=-105.50, y=22.98, z=471.22], EntitySheep['Sheep'/304, l='MpServer', x=-108.50, y=68.00, z=469.50], EntitySheep['Sheep'/305, l='MpServer', x=-111.50, y=70.00, z=470.50], EntityCreeper['Creeper'/316, l='MpServer', x=-207.86, y=43.00, z=334.52], EntityCreeper['Creeper'/317, l='MpServer', x=-208.50, y=43.00, z=335.50], EntitySkeleton['Skeleton'/318, l='MpServer', x=-174.50, y=58.00, z=393.50], EntityBat['Bat'/332, l='MpServer', x=-142.40, y=23.10, z=389.25], EntityPlayerSP['Gentle'/236, l='MpServer', x=-168.23, y=91.00, z=393.62], EntityBat['Bat'/343, l='MpServer', x=-218.81, y=21.36, z=365.24], EntitySquid['Squid'/344, l='MpServer', x=-120.50, y=62.00, z=453.50], EntitySquid['Squid'/345, l='MpServer', x=-121.35, y=59.74, z=445.53], EntitySquid['Squid'/346, l='MpServer', x=-121.50, y=62.00, z=455.50], EntitySquid['Squid'/347, l='MpServer', x=-122.50, y=62.00, z=454.50], EntityChicken['Chicken'/92, l='MpServer', x=-228.57, y=77.00, z=364.06], EntityChicken['Chicken'/93, l='MpServer', x=-231.50, y=78.00, z=371.50], EntityChicken['Chicken'/94, l='MpServer', x=-228.50, y=77.00, z=375.50], EntityChicken['Chicken'/95, l='MpServer', x=-231.34, y=78.00, z=373.19], EntitySkeleton['Skeleton'/96, l='MpServer', x=-233.31, y=17.00, z=415.50], EntitySkeleton['Skeleton'/97, l='MpServer', x=-232.50, y=17.00, z=417.50], EntityZombie['Zombie'/104, l='MpServer', x=-217.20, y=40.00, z=332.50], EntityZombie['Zombie'/105, l='MpServer', x=-213.68, y=40.00, z=332.56], EntitySkeleton['Skeleton'/106, l='MpServer', x=-209.50, y=12.00, z=341.50], EntitySkeleton['Skeleton'/107, l='MpServer', x=-211.50, y=12.00, z=345.50], EntityCreeper['Creeper'/108, l='MpServer', x=-208.50, y=12.00, z=341.50], EntityZombie['Zombie'/109, l='MpServer', x=-219.50, y=20.00, z=365.50], EntityItem['item.item.arrow'/110, l='MpServer', x=-218.88, y=76.00, z=355.05], EntityChicken['Chicken'/111, l='MpServer', x=-214.14, y=80.00, z=391.62], EntityChicken['Chicken'/112, l='MpServer', x=-220.63, y=76.00, z=413.95], EntityChicken['Chicken'/113, l='MpServer', x=-223.50, y=77.00, z=410.50], EntityChicken['Chicken'/114, l='MpServer', x=-218.50, y=75.00, z=415.50], EntityChicken['Chicken'/115, l='MpServer', x=-220.41, y=76.00, z=413.18], EntitySkeleton['Skeleton'/121, l='MpServer', x=-205.50, y=12.00, z=337.50], EntityCreeper['Creeper'/122, l='MpServer', x=-207.50, y=12.00, z=341.50], EntitySkeleton['Skeleton'/123, l='MpServer', x=-203.50, y=47.00, z=355.50], EntityBat['Bat'/124, l='MpServer', x=-204.11, y=46.16, z=356.78], EntityBat['Bat'/125, l='MpServer', x=-202.05, y=45.46, z=370.94], EntityCreeper['Creeper'/126, l='MpServer', x=-203.27, y=41.00, z=397.56], EntityCreeper['Creeper'/127, l='MpServer', x=-201.50, y=41.00, z=398.50], EntityChicken['Chicken'/128, l='MpServer', x=-204.50, y=79.00, z=396.50], EntityChicken['Chicken'/129, l='MpServer', x=-204.72, y=82.00, z=389.57], EntityChicken['Chicken'/130, l='MpServer', x=-203.50, y=83.00, z=386.04], EntityChicken['Chicken'/131, l='MpServer', x=-192.82, y=87.00, z=388.44], EntityChicken['Chicken'/132, l='MpServer', x=-203.20, y=82.00, z=388.45], EntityChicken['Chicken'/133, l='MpServer', x=-205.50, y=80.00, z=395.50], EntityChicken['Chicken'/134, l='MpServer', x=-203.50, y=80.00, z=395.50], EntityZombie['Zombie'/138, l='MpServer', x=-186.50, y=39.00, z=392.50], EntitySpider['Spider'/139, l='MpServer', x=-184.89, y=39.00, z=398.19], EntitySpider['Spider'/140, l='MpServer', x=-185.73, y=39.00, z=396.67], EntitySpider['Spider'/141, l='MpServer', x=-186.68, y=39.00, z=395.19], EntityZombie['Zombie'/142, l='MpServer', x=-180.50, y=30.00, z=406.50], EntityBat['Bat'/143, l='MpServer', x=-178.62, y=32.10, z=403.53], EntityZombieVillager['Zombie Villager'/145, l='MpServer', x=-165.50, y=39.00, z=345.50], EntitySkeleton['Skeleton'/146, l='MpServer', x=-174.50, y=19.00, z=366.50], EntityZombie['Zombie'/147, l='MpServer', x=-161.51, y=33.00, z=386.71], EntityCreeper['Creeper'/148, l='MpServer', x=-163.99, y=35.00, z=406.66], EntityBat['Bat'/149, l='MpServer', x=-169.39, y=35.10, z=419.25], EntityBat['Bat'/152, l='MpServer', x=-164.94, y=30.84, z=357.55], EntityWitch['Witch'/153, l='MpServer', x=-157.50, y=43.00, z=369.50], EntityWitch['Witch'/154, l='MpServer', x=-155.50, y=43.00, z=371.50], EntityZombie['Zombie'/155, l='MpServer', x=-144.52, y=41.00, z=381.80], EntityZombie['Zombie'/156, l='MpServer', x=-159.50, y=55.00, z=385.50], EntityZombie['Zombie'/157, l='MpServer', x=-147.50, y=36.00, z=411.50], EntitySkeleton['Skeleton'/158, l='MpServer', x=-148.50, y=36.00, z=411.50], EntityZombie['Zombie'/163, l='MpServer', x=-141.50, y=33.00, z=397.50], EntityZombie['Zombie'/164, l='MpServer', x=-143.50, y=34.00, z=399.50], EntityChicken['Chicken'/165, l='MpServer', x=-135.42, y=64.00, z=392.88], EntityChicken['Chicken'/166, l='MpServer', x=-126.26, y=72.40, z=404.47], EntityChicken['Chicken'/167, l='MpServer', x=-130.95, y=70.00, z=405.62], EntityZombie['Zombie'/176, l='MpServer', x=-117.50, y=41.00, z=332.50], EntityCreeper['Creeper'/177, l='MpServer', x=-122.50, y=18.00, z=348.50], EntityChicken['Chicken'/178, l='MpServer', x=-126.89, y=72.00, z=406.52], EntityChicken['Chicken'/179, l='MpServer', x=-117.50, y=63.00, z=416.50], EntityChicken['Chicken'/180, l='MpServer', x=-118.50, y=64.00, z=416.50], EntityChicken['Chicken'/181, l='MpServer', x=-119.50, y=65.00, z=416.50], EntityChicken['Chicken'/182, l='MpServer', x=-119.50, y=65.00, z=417.50], EntityChicken['Chicken'/203, l='MpServer', x=-97.50, y=76.00, z=321.45], EntityChicken['Chicken'/204, l='MpServer', x=-97.62, y=84.00, z=327.61], EntityChicken['Chicken'/205, l='MpServer', x=-99.50, y=83.00, z=327.50], EntityChicken['Chicken'/215, l='MpServer', x=-95.82, y=84.00, z=326.21], EntitySheep['Sheep'/239, l='MpServer', x=-247.57, y=78.00, z=454.80], EntitySheep['Sheep'/240, l='MpServer', x=-246.50, y=78.00, z=455.50], EntitySheep['Sheep'/241, l='MpServer', x=-247.02, y=78.00, z=453.76], EntitySheep['Sheep'/242, l='MpServer', x=-245.50, y=78.00, z=452.50], EntityChicken['Chicken'/243, l='MpServer', x=-242.50, y=79.00, z=441.50], EntityChicken['Chicken'/244, l='MpServer', x=-245.50, y=79.00, z=440.50], EntityChicken['Chicken'/245, l='MpServer', x=-246.55, y=79.00, z=444.53], EntityChicken['Chicken'/246, l='MpServer', x=-246.50, y=79.00, z=443.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server

-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 324923696 bytes (309 MB) / 920387584 bytes (877 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 10 total; -XX:HeapDumpPath=ThisTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M -Xms256M -Xmn128M -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.41 Powered by Forge 14.22.1.2480 Optifine OptiFine_1.12.1_HD_U_C5 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID              | Version               | Source                            | Signature                                |
	|:--------- |:--------------- |:--------------------- |:--------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft       | 1.12.1                | minecraft.jar                     | None                                     |
	| UCHIJAAAA | mcp             | 9.19                  | minecraft.jar                     | None                                     |
	| UCHIJAAAA | FML             | 8.0.99.99             | forge-1.12.1-14.22.1.2480.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge           | 14.22.1.2480          | forge-1.12.1-14.22.1.2480.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | betterfonts     | 1.9.1                 | minecraft.jar                     | None                                     |
	| UCHIJAAAA | advancedhud     | 0.1.11                | AdvancedHUD-1.12-0.1.11.jar       | None                                     |
	| UCHIJAAAA | fw              | 1.6.0                 | FullscreenWindowed-1.12-1.6.0.jar | None                                     |
	| UCHIJAAAA | hud             | 1.3.9                 | hud-1.3.9-1.12.jar.zip            | None                                     |
	| UCHIJAAAA | inventorytweaks | 1.63+beta.108.6ff67c4 | InventoryTweaks-1.63+beta.108.jar | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | mousetweaks     | 2.8                   | MouseTweaks-2.8-mc1.12.1.jar      | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.108.jar)
  invtweaks.forge.asm.ContainerTransformer
BetterFontsCore (TTFR-1.12.1-1.9.1.jar)
  cubex2.ttfr.BFClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.53' Renderer: 'GeForce GTX 960M/PCIe/SSE2'
	Launched Version: 1.12.1
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960M/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.53, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Default Improved 1.12.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.12.1_HD_U_C5
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS-v11.0 Mod
	OpenGlVersion: 4.5.0 NVIDIA 382.53
	OpenGlRenderer: GeForce GTX 960M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by Gentle888** [comment]
I figured out, that World Downloader causes this error.
Here's link to download it if you need to test: https://github.com/Pokechu22/WorldDownloader/releases

**Comment by Gentle888** [comment]
I realized, that after any action with Tabbychat I still get crashes. This is one w/o WorldDownloader.
[crash-2017-09-20_03.27.03-client.txt](https://github.com/crazysnailboy/AdvancedHUD/files/1316046/crash-2017-09-20_03.27.03-client.txt)

**Comment by Gentle888** [comment]
After I get done within AdvancedHUD configurator I get crashed, also, I'm not able to see any HUD elements rendered with AdvancedHUD.

EDIT: Elements were not rendering because of /gamemode 1. :P

**Comment by crazysnailboy** [comment]
I've uploaded v0.1.12 which fixes the subtitle bug. Can you confirm that the elements not rendering was because you were in the wrong game mode and that they actually render OK?

**Comment by Gentle888** [comment]
Everything now working as it should!

**Comment by crazysnailboy** [comment]
Excellent!
